### ISSUE TITLE
General Question on the N4P Klipper

### ISSUE THREAD

**Issue by michael2608H** [mairyj/Elegoo-Neptune-4-Series#3]
Hi, 
I like your additions to the N4P and I don't think many are on the same level. I used to run an Ender 3 with Octopi and since Elegoo has pretty much broken Klipper, I want to go back to the Octopi. But I need the address of MCU somehow. Normally this would work with ls /dev/serial/by-id/*. N4P does not recognise this command. Do you have any idea? Thank you

**Comment by mairyj** [comment]
Hello unfortunately here the OS is on the motherboard and therefore the
address of the mcu is not in the same place ;-)
the address is serial: /dev/ttyS0
But I don't understand what you want to do? because here everything works
correctly for me.

Le jeu. 14 déc. 2023 à 18:42, michael2608H ***@***.***> a
écrit :
